export const defaultProducts = [
  { id: 1, nombre: 'Midnight club', precio: 15000, imagen: 'imgtienda/Midnight_Club-Los_Angeles.jpg' },
  { id: 2, nombre: 'Fifa street 2', precio: 10000, imagen: 'imgtienda/fifastreet.jpg' },
  { id: 3, nombre: 'Black', precio: 5000, imagen: 'imgtienda/black.jpg' },
  { id: 4, nombre: 'Burnout 3: takedown', precio: 18000, imagen: 'imgtienda/burnout 3.jpg' },
  { id: 5, nombre: 'Dragon ball tenkaichi 3', precio: 13000, imagen: 'imgtienda/dragonball.webp' },
  { id: 6, nombre: 'Peak', precio: 5500, imagen: 'imgtienda/peak.jpg' },
  { id: 7, nombre: 'Zelda: Ocarina of time', precio: 60000, imagen: 'imgtienda/zelda.jpg' },
  { id: 8, nombre: 'The outlast trials', precio: 34000, imagen: 'imgtienda/the oullasttrials.jpg' },
  { id: 9, nombre: 'Undertale', precio: 8000, imagen: 'imgtienda/undertae.webp' },
  { id: 10, nombre: 'NFS: shift', precio: 25000, imagen: 'imgtienda/nfs shift.jpg' },
  { id: 11, nombre: 'Bordelands 2', precio: 6500, imagen: 'imgtienda/bordelands 2.jpg' },
  { id: 12, nombre: 'Warcraft 3: Frozen throne', precio: 15000, imagen: 'imgtienda/warcraft 3.webp' },
  { id: 13, nombre: 'Gran turismo 5', precio: 20000, imagen: 'imgtienda/gran turismo 5.jpg' },
  { id: 14, nombre: 'Dead by daylight', precio: 10000, imagen: 'imgtienda/dbd.jpg' },
  { id: 15, nombre: 'Transformers: the game', precio: 15500, imagen: 'imgtienda/transformersgame.jpg' },
  { id: 16, nombre: 'Gran turismo 4', precio: 17000, imagen: 'imgtienda/granturismo4.jpg' },
  { id: 17, nombre: 'Detroit', precio: 15000, imagen: 'imgtienda/detroit.jpg' },
  { id: 18, nombre: 'Red dead redemption 2', precio: 20000, imagen: 'imgtienda/rdr2.webp' },
  { id: 19, nombre: 'Papers please', precio: 8000, imagen: 'imgtienda/papersplease.webp' },
  { id: 20, nombre: 'Mortal kombat 1', precio: 67000, imagen: 'imgtienda/incompleto1.jpg' },
  { id: 21, nombre: 'Resident evil requiem', precio: 40000, imagen: 'imgtienda/rd9.jpg' },
  { id: 22, nombre: 'Pink extinct reprieve 2', precio: 22000, imagen: 'imgtienda/pink extinct reprieve 2.jpg' },
  { id: 23, nombre: 'Webfishing', precio: 3000, imagen: 'imgtienda/webfishing.jpg' },
  { id: 24, nombre: 'Automobilista 2', precio: 9000, imagen: 'imgtienda/at2.jpg' },
  { id: 25, nombre: 'Left 4 dead 2', precio: 5500, imagen: 'imgtienda/left 4 dead 2.jpg' },
  { id: 26, nombre: 'Cyberpunk', precio: 25500, imagen: 'imgtienda/cyberpunk.webp' },
  { id: 27, nombre: 'GTA VI', precio: 100000, imagen: 'imgtienda/gta6.webp' },
  { id: 28, nombre: 'Blue alive condemnation 2', precio: 21000, imagen: 'imgtienda/blue alive condemnation 2.png' },
];
