import { useState } from 'react';
import { defaultProducts } from '../lib/products';
import { formatCLP, readStorage, writeStorage } from '../lib/storage';

const defaultUsers = [
  { nombre: 'Cristian Orlando', email: 'cristian@admin.com', rol: 'Administrador' },
  { nombre: 'Juan Pérez', email: 'juan@gmail.com', rol: 'Cliente' },
  { nombre: 'Mixin', email: 'mixin@admin.com', rol: 'Administrador' },
];

export default function AdminPage() {
  const [products, setProducts] = useState(() => readStorage('productosTienda', defaultProducts));
  const [users, setUsers] = useState(() => readStorage('usuariosAdmin', defaultUsers));
  const [tab, setTab] = useState('products');
  const [productModal, setProductModal] = useState(null);
  const [userModal, setUserModal] = useState(null);

  function saveProducts(next) { setProducts(next); writeStorage('productosTienda', next); }
  function saveUsers(next) { setUsers(next); writeStorage('usuariosAdmin', next); }
  function openProduct(index = null) { setProductModal(index === null ? { index: null, nombre: '', precio: '', imagen: '' } : { index, ...products[index] }); }
  function submitProduct(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const product = { nombre: form.get('nombre').trim(), precio: Number(form.get('precio')), imagen: form.get('imagen').trim() }; const next = [...products]; if (productModal.index === null) next.push({ id: Date.now(), ...product }); else next[productModal.index] = { ...next[productModal.index], ...product }; saveProducts(next); setProductModal(null); }
  function removeProduct(index) { if (confirm('¿Estás seguro de eliminar este producto?')) saveProducts(products.filter((_, i) => i !== index)); }
  function openUser(index = null) { setUserModal(index === null ? { index: null, nombre: '', email: '', rol: 'Cliente' } : { index, ...users[index] }); }
  function submitUser(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const user = { nombre: form.get('nombre').trim(), email: form.get('email').trim(), rol: form.get('rol') }; const next = [...users]; if (userModal.index === null) next.push(user); else next[userModal.index] = user; saveUsers(next); setUserModal(null); }
  function removeUser(index) { if (confirm('¿Estás seguro de eliminar este usuario?')) saveUsers(users.filter((_, i) => i !== index)); }

  return (
    <div className="container my-5">
      <h2 className="mb-4">Gestión del Sistema</h2>
      <ul className="nav nav-tabs mb-4"><li className="nav-item"><button type="button" className={`nav-link ${tab === 'products' ? 'active' : ''}`} onClick={() => setTab('products')}>Productos</button></li><li className="nav-item"><button type="button" className={`nav-link ${tab === 'users' ? 'active' : ''}`} onClick={() => setTab('users')}>Usuarios</button></li></ul>
      {tab === 'products' ? <section><div className="d-flex justify-content-between align-items-center mb-3"><h4>Inventario de Productos</h4><button type="button" className="btn btn-success" onClick={() => openProduct()}>Nuevo Producto</button></div><div className="table-responsive"><table className="table table-dark table-striped align-middle"><thead><tr><th>Imagen</th><th>Nombre</th><th>Precio</th><th className="text-center">Acciones</th></tr></thead><tbody>{products.map((product, index) => <tr key={product.id ?? `${product.nombre}-${index}`}><td><img src={`/${product.imagen}`} style={{ width: '40px', height: '50px', objectFit: 'cover' }} className="rounded" alt={product.nombre} /></td><td>{product.nombre}</td><td>{formatCLP(product.precio)}</td><td className="text-center"><button type="button" className="btn btn-sm btn-outline-warning me-1" onClick={() => openProduct(index)}><i className="bi bi-pencil" /></button><button type="button" className="btn btn-sm btn-outline-danger" onClick={() => removeProduct(index)}><i className="bi bi-trash" /></button></td></tr>)}</tbody></table></div></section> : <section><div className="d-flex justify-content-between align-items-center mb-3"><h4>Lista de Usuarios</h4><button type="button" className="btn btn-warning text-dark fw-bold" onClick={() => openUser()}>Nuevo Usuario</button></div><div className="table-responsive"><table className="table table-dark table-striped"><thead><tr><th>Nombre</th><th>Email</th><th>Rol</th><th className="text-center">Acciones</th></tr></thead><tbody>{users.map((user, index) => <tr key={`${user.email}-${index}`}><td>{user.nombre}</td><td>{user.email}</td><td><span className={`badge ${user.rol === 'Administrador' ? 'bg-danger' : 'bg-info'}`}>{user.rol}</span></td><td className="text-center"><button type="button" className="btn btn-sm btn-outline-warning me-1" onClick={() => openUser(index)}><i className="bi bi-pencil" /></button><button type="button" className="btn btn-sm btn-outline-danger" onClick={() => removeUser(index)}><i className="bi bi-trash" /></button></td></tr>)}</tbody></table></div></section>}
      {productModal && <div className="modal fade show d-block" tabIndex="-1" role="dialog" aria-modal="true"><div className="modal-dialog"><div className="modal-content bg-dark text-white"><form onSubmit={submitProduct}><div className="modal-header"><h5 className="modal-title">{productModal.index === null ? 'Nuevo Producto' : 'Editar Producto'}</h5><button type="button" className="btn-close btn-close-white" onClick={() => setProductModal(null)} aria-label="Cerrar" /></div><div className="modal-body"><div className="mb-3"><label htmlFor="prodNombre" className="form-label">Nombre del Juego</label><input name="nombre" defaultValue={productModal.nombre} id="prodNombre" className="form-control" required /></div><div className="mb-3"><label htmlFor="prodPrecio" className="form-label">Precio ($ CLP)</label><input name="precio" defaultValue={productModal.precio} id="prodPrecio" type="number" className="form-control" required /></div><div className="mb-3"><label htmlFor="prodImagen" className="form-label">Ruta de Imagen</label><input name="imagen" defaultValue={productModal.imagen} id="prodImagen" className="form-control" placeholder="imgtienda/juego.jpg" required /></div></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={() => setProductModal(null)}>Cancelar</button><button type="submit" className="btn btn-primary">Guardar Producto</button></div></form></div></div></div>}
      {userModal && <div className="modal fade show d-block" tabIndex="-1" role="dialog" aria-modal="true"><div className="modal-dialog"><div className="modal-content bg-dark text-white"><form onSubmit={submitUser}><div className="modal-header"><h5 className="modal-title">{userModal.index === null ? 'Nuevo Usuario' : 'Editar Usuario'}</h5><button type="button" className="btn-close btn-close-white" onClick={() => setUserModal(null)} aria-label="Cerrar" /></div><div className="modal-body"><div className="mb-3"><label htmlFor="userNombre" className="form-label">Nombre Completo</label><input name="nombre" defaultValue={userModal.nombre} id="userNombre" className="form-control" required /></div><div className="mb-3"><label htmlFor="userEmail" className="form-label">Correo Electrónico</label><input name="email" defaultValue={userModal.email} id="userEmail" type="email" className="form-control" required /></div><div className="mb-3"><label htmlFor="userRol" className="form-label">Rol</label><select name="rol" defaultValue={userModal.rol} id="userRol" className="form-select"><option>Cliente</option><option>Administrador</option></select></div></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={() => setUserModal(null)}>Cancelar</button><button type="submit" className="btn btn-primary">Guardar Usuario</button></div></form></div></div></div>}
      {(productModal || userModal) && <div className="modal-backdrop fade show" />}
    </div>
  );
}
